version: '3.7'
services: 
  node-app:
    build: ./artifacts/gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
  
services:
  db:
    image: postgres:12.0-alpine
    container_name: pstg-container
    ports: 
        - '5432:5432'
    volumes:
        - ./data:/var/lib/postgresql/datapstg
    environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=app
        - POSTGRES_DB=app
        
services:
  mysql:
    image: mysql:8.0.18
    container_name: mysql-container
    command: --innodb_use_native_aio=0
    ports: 
        - '3306:3306'
    volumes:
        - ./data:/var/lib/mysql
    environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=pass
        
