version: '3.7'
services: 
  node-app:
    build: ./artifacts/gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'
  
  postgres:
    image: postgres:12.0-alpine
    container_name: pstg-container
    ports: 
        - '5432:5432'
    volumes:
        - ./data:/var/lib/postgresql/datapstg
    environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=app
        - POSTGRES_DB=app
        

